corrections of small mistakes in power plant description
openENTRANCE/nomenclature pull request #79
Opened 2020-11-12 15:45 UTC by sandrinecharousset

Includes following corrections:
- traditionnal => traditional (for some instances)
- reservoir => Reservoir (for some instances)
- some run of river variables were wrongly named reservoir
- added missing variable turbine efficiency

2020-11-13 08:26 UTC, erikfilias approved these changes
Thank you, @sandrinecharousset, for the corrections.

2020-11-13 08:28 UTC, erikfilias commented
The conflicts could be solved by a rebase of the branch, I think

2020-11-13 08:31 UTC, erikfilias commented
This branch is outdated, no? Because #80 was created. If it is the case, please closes this PR.

2020-11-13 08:33 UTC, erikfilias commented
Could you solve the conflict, please?

2020-11-13 08:56 UTC, sandrinecharousset commented
> Could you solve the conflict, please? It could be made by a rebase or checking the power-plant.yaml.
> Thanks in advance.

I hope I did what was expected.....

2020-11-13 09:23 UTC, erikfilias approved these changes

2020-12-04 14:42 UTC, danielhuppmann requested changes
Thanks @sandrinecharousset for these clarifications, apologies for the late review - a few minor changes suggested, then good to be merged.

2020-12-04 14:42 UTC, danielhuppmann commented on nomenclature/definitions/variable/technology/power-plant.yaml
> +Maximum Active power|Electricity|Biomass|Traditional:
Suggest minor editorial change to use only capitalized words in variable names
```suggestion
   
Maximum Active Power|Electricity|Biomass|Traditional:
```

2020-12-04 14:42 UTC, danielhuppmann commented on nomenclature/definitions/variable/technology/power-plant.yaml
> +Minimum Active power|Electricity|Biomass|Traditional:
```suggestion
Minimum Active Power|Electricity|Biomass|Traditional:
```

2020-12-04 14:42 UTC, danielhuppmann commented on nomenclature/definitions/variable/technology/power-plant.yaml
> +Minimum Active power|Electricity|Biomass|New and imported:
```suggestion
Minimum Active Power|Electricity|Biomass|New and imported:
```

2020-12-08 14:19 UTC, danielhuppmann approved these changes
Thank you @sandrinecharousset!

2020-12-08 14:20 UTC, merged